server:
  port: 8090

spring:
  application:
    name: backend-service
  devtools:
    restart:
      aditional-paths: src/main/java
  jpa:
    show-sql: true
    hibernate:
      dialect: MySQL8Dialect
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbname: backendDB
    url: jdbc:mysql://localhost:3306/backendDB
    username: root
    password: admin    
