server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Harunomi/PEP3_Tingeso_1-2023
          search-paths: config-data
  application:
    name: config-service
